# Generated by Django 3.2.7 on 2021-09-17 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacinacao',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='vacinacao',
            name='vacina',
        ),
        migrations.AddField(
            model_name='vacinacao',
            name='data',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='PontoVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vacina.local')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vacina.vacina')),
            ],
        ),
        migrations.AddField(
            model_name='vacinacao',
            name='ponto_vacinacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_vacina.pontovacinacao'),
        ),
    ]
